version: "2.6.0"

services:
  mysql:
    image: mysql:8.0
    container_name: 'mysql-server1'
    environment:
      MYSQL_ROOT_PASSWORD: 1
    ports:
      - 3306:3306

  redis:
    image: redis:5.0
    container_name: 'redis-server1'
    ports:
      - 6379:6379